FROM gcr.io/distroless/cc

ARG TARGETARCH

COPY --chown=65532:65532 image-bin/${TARGETARCH}/memoro /usr/local/bin/memoro
COPY --chown=65532:65532 image-data/.keep /data/.keep

ENV MEMORO_HOME=/data
VOLUME /data
EXPOSE 8000
USER nonroot:nonroot

CMD ["memoro", "serve", "--transport", "http", "--host", "0.0.0.0"]
